[package]
name = "tairitsu"
version = "0.2.0"
edition = "2021"

publish = true
authors = ["langyo <langyo.china@gmail.com>"]
description = "A WebAssembly runtime for running component-model based WASM modules"
license = "Apache-2.0"
repository = "https://github.com/celestia-island/tairitsu"

[dependencies]
tairitsu-macros = "0.2.0"

anyhow = "^1"
bytes = "^1"

wasmtime = { version = "^40", features = ["component-model"] }
wasmtime-wasi = "^40"
wit-component = "^0.243"
